

#注释
#1.字典格式：键： 值
#usrname: sadda
#password: asdd
#
#derss:
#  xing: pop
#  ming: 123456
#2.列表格式：-
#- 10
#- 20
#- 30
#- 40
#- 50
#-
#  - 100
#  - 200
#  - 300
#  - 400
#3.列表套字典
#-
#  name: ming
#  word: zi
#4.字典套列表
#name: yun
#ming:
#  - 200
#  - 600
#  - 999

#5.引号处理,1.如果有特殊字符，不加引号就原样输出
        #2.如果要需要特殊字符的显示效果，加个双引号

#6.变量的引用
#info: &a "helloword"
#jieguo: *a

#7.多个yaml文件写在一起
#用--- 分割

#xing: gao
#yun: liang
#---
#- 100
#- 200
#- 300

#8 yaml用例的设计












